import type { PlatformLocale } from "@/lib/i18n/config";

type MethodologySection = { title: string; paragraphs: readonly string[]; bullets?: readonly string[] };
type MethodologyMessages = {
  title: string;
  intro: string;
  contactLead: string;
  sections: readonly MethodologySection[];
};

export const METHODOLOGY_MESSAGES: Record<PlatformLocale, MethodologyMessages> = {
  it: {
    title: "Fonti e metodologia",
    intro: "Immigrati Imprenditori utilizza fonti statistiche, istituzionali, accademiche, associative, giornalistiche e testimonianze dirette in relazione alla natura dei contenuti pubblicati.",
    contactLead: "Per segnalare un errore o proporre una fonte:",
    sections: [
      { title: "Identificazione delle fonti", paragraphs: ["Quando un dato o un'informazione deriva da una fonte esterna, il Centro Studi indica la fonte primaria quando disponibile e, ove pertinenti, periodo di riferimento, territorio, unità di misura, metodologia, data di aggiornamento ed eventuali limiti.", "Una fonte secondaria che commenta o riprende un dato non viene presentata come fonte primaria del dato stesso."] },
      { title: "Dati e indicatori", paragraphs: ["L'Osservatorio raccoglie e organizza indicatori e serie storiche mantenendo separati, per quanto possibile, il valore pubblicato dalla fonte, le elaborazioni del Centro Studi e le interpretazioni editoriali.", "Ogni scheda dell'Osservatorio deve rendere identificabili almeno l'indicatore, il periodo, il territorio, l'unità di misura, la fonte e la nota metodologica necessaria per interpretare correttamente il dato."] },
      { title: "Definizioni e comparabilità", paragraphs: ["Le espressioni imprenditore migrante, impresa straniera, lavoratore autonomo, cittadino straniero e persona nata all'estero non sono sinonimi. Le fonti possono misurare fenomeni diversi e utilizzare criteri differenti.", "Per questo motivo il Centro Studi non somma e non confronta direttamente valori costruiti con definizioni, popolazioni, territori, periodi o unità non compatibili. Quando viene effettuato un confronto, la base metodologica deve essere esplicita.", "Le differenze di definizione, copertura geografica, periodo o metodologia possono rendere non direttamente confrontabili dati provenienti da fonti diverse. Le note metodologiche delle singole schede prevalgono sulle sintesi generali."], bullets: ["I dati del Registro Imprese misurano imprese e applicano le definizioni previste dalla fonte camerale.", "Le statistiche sul lavoro autonomo misurano persone occupate in una determinata condizione professionale, non il numero di imprese.", "La cittadinanza e il luogo di nascita sono variabili statistiche distinte.", "Una persona può essere imprenditore migrante senza rientrare nella stessa categoria utilizzata da una specifica fonte statistica, e viceversa."] },
      { title: "Elaborazioni del Centro Studi", paragraphs: ["Quando un valore viene trasformato per uniformare l'unità di misura — per esempio convertendo migliaia di persone in persone — la trasformazione deve essere documentata senza modificare il significato statistico del dato di origine.", "Le elaborazioni proprie devono restare distinguibili dai valori direttamente pubblicati dalla fonte."] },
      { title: "Aggiornamenti e correzioni", paragraphs: ["I dati e i contenuti possono essere aggiornati quando una fonte pubblica una revisione, quando emergono informazioni più complete o quando viene verificato un errore. Le correzioni sostanziali seguono la politica editoriale e di correzione del Centro Studi."] },
      { title: "Link e materiali esterni", paragraphs: ["I collegamenti a siti esterni sono forniti per documentazione e approfondimento. La presenza di un link non implica approvazione generale dei contenuti, delle opinioni o dei servizi presenti nel sito esterno.", "Materiali, marchi, dataset e documenti di terzi restano soggetti ai diritti, alle licenze e alle condizioni stabilite dai rispettivi titolari."] },
      { title: "Uso delle informazioni", paragraphs: ["Le informazioni pubblicate hanno finalità di studio, documentazione e informazione. Chi utilizza dati o contenuti per decisioni professionali, economiche, amministrative o giuridiche deve verificare la fonte originale e il contesto metodologico pertinente."] },
    ],
  },
  en: {
    title: "Sources & methodology",
    intro: "Immigrati Imprenditori uses statistical, institutional, academic, association and journalistic sources, as well as direct testimony, according to the nature of the published material.",
    contactLead: "To report an error or propose a source:",
    sections: [
      { title: "Identifying sources", paragraphs: ["When data or information derives from an external source, the Research Centre identifies the primary source whenever available and, where relevant, the reference period, territory, unit of measurement, methodology, update date and any limitations.", "A secondary source that comments on or reproduces a value is not presented as the primary source of that value."] },
      { title: "Data and indicators", paragraphs: ["The Observatory collects and organises indicators and time series while keeping, as far as possible, the value published by the source, Research Centre processing and editorial interpretation separate.", "Each Observatory record must make it possible to identify at least the indicator, period, territory, unit of measurement, source and the methodological note required to interpret the value correctly."] },
      { title: "Definitions and comparability", paragraphs: ["The terms migrant entrepreneur, foreign enterprise, self-employed person, foreign citizen and foreign-born person are not synonyms. Sources may measure different phenomena and use different criteria.", "For this reason, the Research Centre does not directly add or compare values built from incompatible definitions, populations, territories, periods or units. When a comparison is made, its methodological basis must be explicit.", "Differences in definition, geographic coverage, period or methodology may make data from different sources not directly comparable. Methodological notes on individual records take precedence over general summaries."], bullets: ["Business-register data measure enterprises and apply the definitions adopted by the relevant register or chamber source.", "Self-employment statistics measure people working under a particular employment status, not the number of enterprises.", "Citizenship and place of birth are distinct statistical variables.", "A person may be a migrant entrepreneur without belonging to the same category used by a specific statistical source, and vice versa."] },
      { title: "Research Centre processing", paragraphs: ["When a value is transformed to harmonise its unit of measurement — for example by converting thousands of persons into persons — the transformation must be documented without changing the statistical meaning of the original value.", "Research Centre processing must remain distinguishable from values published directly by the source."] },
      { title: "Updates and corrections", paragraphs: ["Data and content may be updated when a source publishes a revision, when more complete information becomes available or when an error is verified. Material corrections follow the Research Centre's editorial and correction policy."] },
      { title: "External links and materials", paragraphs: ["Links to external sites are provided for documentation and further reading. A link does not imply general endorsement of the content, opinions or services available on the external site.", "Third-party materials, trademarks, datasets and documents remain subject to the rights, licences and conditions established by their respective owners."] },
      { title: "Use of information", paragraphs: ["Published information is intended for research, documentation and information purposes. Anyone using data or content for professional, economic, administrative or legal decisions should verify the original source and the relevant methodological context."] },
    ],
  },
  fr: {
    title: "Sources et méthodologie",
    intro: "Immigrati Imprenditori utilise des sources statistiques, institutionnelles, académiques, associatives et journalistiques, ainsi que des témoignages directs, selon la nature des contenus publiés.",
    contactLead: "Pour signaler une erreur ou proposer une source :",
    sections: [
      { title: "Identification des sources", paragraphs: ["Lorsqu'une donnée ou une information provient d'une source externe, le Centre d'études indique la source primaire lorsqu'elle est disponible et, lorsque cela est pertinent, la période de référence, le territoire, l'unité de mesure, la méthodologie, la date de mise à jour et les éventuelles limites.", "Une source secondaire qui commente ou reprend une donnée n'est pas présentée comme la source primaire de cette donnée."] },
      { title: "Données et indicateurs", paragraphs: ["L'Observatoire collecte et organise des indicateurs et des séries chronologiques en maintenant séparés, autant que possible, la valeur publiée par la source, les traitements du Centre d'études et les interprétations éditoriales.", "Chaque fiche de l'Observatoire doit permettre d'identifier au minimum l'indicateur, la période, le territoire, l'unité de mesure, la source et la note méthodologique nécessaire à une interprétation correcte."] },
      { title: "Définitions et comparabilité", paragraphs: ["Les expressions entrepreneur migrant, entreprise étrangère, travailleur indépendant, citoyen étranger et personne née à l'étranger ne sont pas synonymes. Les sources peuvent mesurer des phénomènes différents et utiliser des critères distincts.", "Pour cette raison, le Centre d'études n'additionne ni ne compare directement des valeurs construites à partir de définitions, populations, territoires, périodes ou unités incompatibles. Lorsqu'une comparaison est effectuée, sa base méthodologique doit être explicite.", "Des différences de définition, couverture géographique, période ou méthodologie peuvent rendre non directement comparables des données provenant de sources différentes. Les notes méthodologiques des fiches individuelles prévalent sur les synthèses générales."], bullets: ["Les données des registres d'entreprises mesurent des entreprises et appliquent les définitions de la source consulaire ou du registre concerné.", "Les statistiques sur le travail indépendant mesurent des personnes exerçant sous un statut professionnel déterminé, et non le nombre d'entreprises.", "La citoyenneté et le lieu de naissance sont des variables statistiques distinctes.", "Une personne peut être un entrepreneur migrant sans relever de la même catégorie qu'une source statistique particulière, et inversement."] },
      { title: "Traitements du Centre d'études", paragraphs: ["Lorsqu'une valeur est transformée afin d'harmoniser l'unité de mesure — par exemple en convertissant des milliers de personnes en personnes — la transformation doit être documentée sans modifier le sens statistique de la donnée d'origine.", "Les traitements propres au Centre d'études doivent rester distinguables des valeurs directement publiées par la source."] },
      { title: "Mises à jour et corrections", paragraphs: ["Les données et contenus peuvent être mis à jour lorsqu'une source publie une révision, lorsque des informations plus complètes apparaissent ou lorsqu'une erreur est vérifiée. Les corrections substantielles suivent la politique éditoriale et de correction du Centre d'études."] },
      { title: "Liens et matériels externes", paragraphs: ["Les liens vers des sites externes sont fournis à des fins de documentation et d'approfondissement. La présence d'un lien n'implique pas une approbation générale des contenus, opinions ou services du site externe.", "Les matériels, marques, jeux de données et documents de tiers restent soumis aux droits, licences et conditions définis par leurs titulaires respectifs."] },
      { title: "Utilisation des informations", paragraphs: ["Les informations publiées ont une finalité d'étude, de documentation et d'information. Toute personne utilisant des données ou contenus pour des décisions professionnelles, économiques, administratives ou juridiques doit vérifier la source originale et le contexte méthodologique pertinent."] },
    ],
  },
  es: {
    title: "Fuentes y metodología",
    intro: "Immigrati Imprenditori utiliza fuentes estadísticas, institucionales, académicas, asociativas y periodísticas, además de testimonios directos, según la naturaleza de los contenidos publicados.",
    contactLead: "Para comunicar un error o proponer una fuente:",
    sections: [
      { title: "Identificación de las fuentes", paragraphs: ["Cuando un dato o una información procede de una fuente externa, el Centro de Estudios indica la fuente primaria cuando está disponible y, cuando corresponde, el periodo de referencia, territorio, unidad de medida, metodología, fecha de actualización y posibles limitaciones.", "Una fuente secundaria que comenta o reproduce un dato no se presenta como fuente primaria de ese dato."] },
      { title: "Datos e indicadores", paragraphs: ["El Observatorio recopila y organiza indicadores y series temporales manteniendo separados, en la medida de lo posible, el valor publicado por la fuente, las elaboraciones del Centro de Estudios y las interpretaciones editoriales.", "Cada ficha del Observatorio debe permitir identificar al menos el indicador, periodo, territorio, unidad de medida, fuente y la nota metodológica necesaria para interpretar correctamente el dato."] },
      { title: "Definiciones y comparabilidad", paragraphs: ["Las expresiones emprendedor migrante, empresa extranjera, trabajador autónomo, ciudadano extranjero y persona nacida en el extranjero no son sinónimos. Las fuentes pueden medir fenómenos diferentes y utilizar criterios distintos.", "Por esta razón, el Centro de Estudios no suma ni compara directamente valores construidos con definiciones, poblaciones, territorios, periodos o unidades incompatibles. Cuando se realiza una comparación, su base metodológica debe ser explícita.", "Las diferencias de definición, cobertura geográfica, periodo o metodología pueden hacer que datos de distintas fuentes no sean directamente comparables. Las notas metodológicas de cada ficha prevalecen sobre los resúmenes generales."], bullets: ["Los datos de registros empresariales miden empresas y aplican las definiciones de la fuente registral o cameral correspondiente.", "Las estadísticas de trabajo autónomo miden personas ocupadas en una determinada situación profesional, no el número de empresas.", "La ciudadanía y el lugar de nacimiento son variables estadísticas distintas.", "Una persona puede ser emprendedor migrante sin pertenecer a la misma categoría utilizada por una fuente estadística específica, y viceversa."] },
      { title: "Elaboraciones del Centro de Estudios", paragraphs: ["Cuando se transforma un valor para homogeneizar la unidad de medida — por ejemplo, convirtiendo miles de personas en personas — la transformación debe documentarse sin modificar el significado estadístico del dato original.", "Las elaboraciones propias deben seguir siendo distinguibles de los valores publicados directamente por la fuente."] },
      { title: "Actualizaciones y correcciones", paragraphs: ["Los datos y contenidos pueden actualizarse cuando una fuente publica una revisión, cuando aparece información más completa o cuando se verifica un error. Las correcciones sustanciales siguen la política editorial y de corrección del Centro de Estudios."] },
      { title: "Enlaces y materiales externos", paragraphs: ["Los enlaces a sitios externos se facilitan para documentación y profundización. La presencia de un enlace no implica una aprobación general de los contenidos, opiniones o servicios presentes en el sitio externo.", "Los materiales, marcas, conjuntos de datos y documentos de terceros siguen sujetos a los derechos, licencias y condiciones establecidos por sus respectivos titulares."] },
      { title: "Uso de la información", paragraphs: ["La información publicada tiene fines de estudio, documentación e información. Quien utilice datos o contenidos para decisiones profesionales, económicas, administrativas o jurídicas debe verificar la fuente original y el contexto metodológico pertinente."] },
    ],
  },
  de: {
    title: "Quellen & Methodik",
    intro: "Immigrati Imprenditori nutzt je nach Art der veröffentlichten Inhalte statistische, institutionelle, akademische, verbandliche und journalistische Quellen sowie direkte Erfahrungsberichte.",
    contactLead: "Fehler melden oder eine Quelle vorschlagen:",
    sections: [
      { title: "Quellenidentifikation", paragraphs: ["Stammen Daten oder Informationen aus einer externen Quelle, nennt das Studienzentrum nach Möglichkeit die Primärquelle sowie, soweit relevant, Bezugszeitraum, Gebiet, Maßeinheit, Methodik, Aktualisierungsdatum und mögliche Einschränkungen.", "Eine Sekundärquelle, die einen Wert kommentiert oder übernimmt, wird nicht als Primärquelle dieses Werts dargestellt."] },
      { title: "Daten und Indikatoren", paragraphs: ["Das Observatorium sammelt und ordnet Indikatoren und Zeitreihen und hält, soweit möglich, den von der Quelle veröffentlichten Wert, Aufbereitungen des Studienzentrums und redaktionelle Interpretationen getrennt.", "Jede Indikatorseite des Observatoriums muss mindestens Indikator, Zeitraum, Gebiet, Maßeinheit, Quelle und die für eine korrekte Interpretation erforderliche methodische Anmerkung erkennen lassen."] },
      { title: "Definitionen und Vergleichbarkeit", paragraphs: ["Die Begriffe migrantischer Unternehmer, ausländisches Unternehmen, selbstständige Person, ausländischer Staatsangehöriger und im Ausland geborene Person sind keine Synonyme. Quellen können unterschiedliche Phänomene messen und verschiedene Kriterien verwenden.", "Daher addiert oder vergleicht das Studienzentrum Werte, die auf inkompatiblen Definitionen, Populationen, Gebieten, Zeiträumen oder Einheiten beruhen, nicht direkt. Wird ein Vergleich vorgenommen, muss seine methodische Grundlage ausdrücklich angegeben werden.", "Unterschiede bei Definition, geografischer Abdeckung, Zeitraum oder Methodik können dazu führen, dass Daten verschiedener Quellen nicht direkt vergleichbar sind. Methodische Hinweise einzelner Indikatorseiten haben Vorrang vor allgemeinen Zusammenfassungen."], bullets: ["Daten aus Unternehmensregistern messen Unternehmen und wenden die Definitionen der jeweiligen Register- oder Kammerquelle an.", "Statistiken zur Selbstständigkeit messen Personen in einem bestimmten Erwerbsstatus, nicht die Zahl der Unternehmen.", "Staatsangehörigkeit und Geburtsort sind unterschiedliche statistische Variablen.", "Eine Person kann migrantischer Unternehmer sein, ohne derselben Kategorie einer bestimmten statistischen Quelle anzugehören, und umgekehrt."] },
      { title: "Aufbereitungen des Studienzentrums", paragraphs: ["Wird ein Wert zur Vereinheitlichung der Maßeinheit transformiert — etwa Tausende von Personen in Personen — muss die Transformation dokumentiert werden, ohne die statistische Bedeutung des Ausgangswerts zu verändern.", "Eigene Aufbereitungen müssen von direkt durch die Quelle veröffentlichten Werten unterscheidbar bleiben."] },
      { title: "Aktualisierungen und Korrekturen", paragraphs: ["Daten und Inhalte können aktualisiert werden, wenn eine Quelle eine Revision veröffentlicht, vollständigere Informationen verfügbar werden oder ein Fehler bestätigt wird. Wesentliche Korrekturen folgen der Redaktions- und Korrekturpolitik des Studienzentrums."] },
      { title: "Externe Links und Materialien", paragraphs: ["Links zu externen Websites dienen der Dokumentation und Vertiefung. Ein Link bedeutet keine allgemeine Billigung der Inhalte, Meinungen oder Dienste der externen Website.", "Materialien, Marken, Datensätze und Dokumente Dritter unterliegen weiterhin den Rechten, Lizenzen und Bedingungen ihrer jeweiligen Rechteinhaber."] },
      { title: "Nutzung der Informationen", paragraphs: ["Die veröffentlichten Informationen dienen Forschung, Dokumentation und Information. Wer Daten oder Inhalte für berufliche, wirtschaftliche, administrative oder rechtliche Entscheidungen nutzt, sollte die Originalquelle und den relevanten methodischen Kontext prüfen."] },
    ],
  },
  ar: {
    title: "المصادر والمنهجية",
    intro: "يستخدم Immigrati Imprenditori مصادر إحصائية ومؤسسية وأكاديمية وجمعوية وصحفية، إضافة إلى شهادات مباشرة، بحسب طبيعة المحتوى المنشور.",
    contactLead: "للإبلاغ عن خطأ أو اقتراح مصدر:",
    sections: [
      { title: "تحديد المصادر", paragraphs: ["عندما تستند بيانات أو معلومات إلى مصدر خارجي، يذكر مركز الدراسات المصدر الأولي متى كان متاحاً، وكذلك عند الاقتضاء الفترة المرجعية والإقليم ووحدة القياس والمنهجية وتاريخ التحديث وأي قيود.", "لا يُعرض المصدر الثانوي الذي يعلق على قيمة أو يعيد نشرها باعتباره المصدر الأولي لتلك القيمة."] },
      { title: "البيانات والمؤشرات", paragraphs: ["يجمع المرصد المؤشرات والسلاسل الزمنية وينظمها مع الحفاظ، قدر الإمكان، على الفصل بين القيمة المنشورة من المصدر ومعالجات مركز الدراسات والتفسيرات التحريرية.", "يجب أن تتيح كل صفحة مؤشر في المرصد تحديد المؤشر والفترة والإقليم ووحدة القياس والمصدر والملاحظة المنهجية اللازمة لفهم القيمة بصورة صحيحة على الأقل."] },
      { title: "التعريفات وقابلية المقارنة", paragraphs: ["مصطلحات رائد الأعمال المهاجر والمنشأة الأجنبية والعامل لحسابه الخاص والمواطن الأجنبي والشخص المولود في الخارج ليست مترادفة. فقد تقيس المصادر ظواهر مختلفة وتستخدم معايير مختلفة.", "لذلك لا يجمع مركز الدراسات ولا يقارن مباشرة قيماً مبنية على تعريفات أو مجموعات سكانية أو أقاليم أو فترات أو وحدات غير متوافقة. وعند إجراء مقارنة يجب توضيح أساسها المنهجي.", "قد تجعل الاختلافات في التعريف أو التغطية الجغرافية أو الفترة أو المنهجية بيانات المصادر المختلفة غير قابلة للمقارنة المباشرة. وتتقدم الملاحظات المنهجية الخاصة بكل صفحة على الملخصات العامة."], bullets: ["تقيس بيانات سجلات الأعمال المنشآت وتطبق التعريفات المعتمدة لدى سجل الأعمال أو الغرفة المعنية.", "تقيس إحصاءات العمل الحر الأشخاص العاملين ضمن وضع مهني محدد، لا عدد المنشآت.", "الجنسية ومكان الميلاد متغيران إحصائيان مختلفان.", "قد يكون الشخص رائد أعمال مهاجراً من دون أن يندرج في الفئة نفسها التي يستخدمها مصدر إحصائي محدد، والعكس صحيح."] },
      { title: "معالجات مركز الدراسات", paragraphs: ["عند تحويل قيمة لتوحيد وحدة القياس — مثل تحويل آلاف الأشخاص إلى أشخاص — يجب توثيق التحويل من دون تغيير المعنى الإحصائي للقيمة الأصلية.", "يجب أن تبقى معالجات مركز الدراسات متميزة عن القيم التي ينشرها المصدر مباشرة."] },
      { title: "التحديثات والتصحيحات", paragraphs: ["يمكن تحديث البيانات والمحتوى عندما ينشر المصدر مراجعة، أو تتوفر معلومات أكثر اكتمالاً، أو يتم التحقق من خطأ. وتتبع التصحيحات الجوهرية سياسة التحرير والتصحيح في مركز الدراسات."] },
      { title: "الروابط والمواد الخارجية", paragraphs: ["تُقدم الروابط إلى المواقع الخارجية لأغراض التوثيق والتعمق. ولا يعني وجود رابط تأييداً عاماً للمحتوى أو الآراء أو الخدمات المتاحة في الموقع الخارجي.", "تظل المواد والعلامات التجارية ومجموعات البيانات ووثائق الأطراف الثالثة خاضعة للحقوق والتراخيص والشروط التي يحددها أصحابها." ] },
      { title: "استخدام المعلومات", paragraphs: ["تهدف المعلومات المنشورة إلى البحث والتوثيق والإعلام. وعلى من يستخدم البيانات أو المحتوى لاتخاذ قرارات مهنية أو اقتصادية أو إدارية أو قانونية أن يتحقق من المصدر الأصلي والسياق المنهجي ذي الصلة."] },
    ],
  },
  zh: {
    title: "来源与方法",
    intro: "Immigrati Imprenditori 根据所发布内容的性质，使用统计、机构、学术、协会和新闻来源，并结合直接证言。",
    contactLead: "如需报告错误或推荐来源：",
    sections: [
      { title: "来源识别", paragraphs: ["当数据或信息来自外部来源时，研究中心会在可获得的情况下标明第一手来源，并在适用时说明参考时期、地区、计量单位、方法、更新时间以及可能存在的限制。", "对某一数据进行评论或转载的第二手来源不会被标示为该数据的第一手来源。"] },
      { title: "数据与指标", paragraphs: ["观察站收集和组织指标及时间序列，并尽可能将来源直接发布的数据值、研究中心的处理结果和编辑性解释彼此区分。", "每个观察站指标页面至少应能够识别指标、时期、地区、计量单位、来源以及正确解释该数据所必需的方法说明。"] },
      { title: "定义与可比性", paragraphs: ["“移民企业家”“外国企业”“自雇人员”“外国公民”和“境外出生人口”并非同义词。不同来源可能衡量不同现象并采用不同标准。", "因此，研究中心不会直接汇总或比较基于不兼容定义、统计总体、地区、时期或单位构建的数据。进行比较时，必须明确其方法基础。", "定义、地理覆盖、时期或方法上的差异，可能使不同来源的数据无法直接比较。各指标页面中的具体方法说明优先于一般性概述。"], bullets: ["企业登记数据衡量企业，并采用相关登记机构或商会来源规定的定义。", "自雇统计衡量处于特定就业状态的人员，而不是企业数量。", "国籍和出生地是不同的统计变量。", "一个人可能属于研究中心所称的移民企业家，但不属于某一特定统计来源使用的同一类别，反之亦然。"] },
      { title: "研究中心的数据处理", paragraphs: ["当为了统一计量单位而转换数据值时——例如将“千人”转换为“人”——必须记录该转换过程，同时不得改变原始数据的统计含义。", "研究中心的处理结果必须能够与来源直接发布的数据值区分开来。"] },
      { title: "更新与更正", paragraphs: ["当来源发布修订、更完整的信息出现或确认存在错误时，数据和内容可以更新。重大更正遵循研究中心的编辑与更正政策。"] },
      { title: "外部链接与材料", paragraphs: ["指向外部网站的链接用于文献记录和进一步了解。提供链接并不意味着研究中心普遍认可外部网站中的内容、观点或服务。", "第三方材料、商标、数据集和文件仍受其各自权利人规定的权利、许可和条件约束。"] },
      { title: "信息使用", paragraphs: ["所发布信息用于研究、文献记录和信息传播。任何将数据或内容用于专业、经济、行政或法律决策的人，都应核查原始来源及相关方法背景。"] },
    ],
  },
};
