import type { PlatformLocale } from "@/lib/i18n/config";

type Locale = Exclude<PlatformLocale, "it">;
type SourceTranslation = { methodology: string | null; license: string | null };

const SOURCE_TRANSLATIONS: Record<Locale, Record<string, SourceTranslation>> = {
  en: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "LFS self-employed by citizenship. Attribution to Eurostat required. Free re-use with acknowledgement. Citizenship is not the same as country of birth or a chamber-of-commerce foreign-controlled enterprise.", license: "Eurostat free re-use with attribution; state modifications if any. Verified 13 August 2026." },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS, age group 20–64. The indicator is the share of self-employed persons in total employment at EU-27 level, by citizenship group. Citizenship is distinct from country of birth and from the Business Register definition of a foreign enterprise.", license: "Eurostat Statistics Explained / EU-LFS. Re-use subject to Eurostat attribution and applicable re-use conditions." },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "Business Register. InfoCamere defines a ‘foreign’ enterprise as one in which the overall participation of natural persons not born in Italy exceeds 50%, combining ownership shares and administrative roles according to the type of enterprise. The figure is not the number of migrant entrepreneurs and should not be compared directly with LFS self-employment indicators.", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "Business Register data processed by InfoCamere within Futurae. The Unioncamere contribution reports the stock of foreign-led enterprises and compares it with the overall business base.", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "Self-employment rate among the employed population, by place of birth. Foreign-born and native-born are population groups, not citizenship categories. For the selected European countries the chapter relies on EU-LFS 2022; the OECD average covers 37 countries. The indicator is not a count of registered firms and should not be treated as the same measure as InfoCamere Business Register data.", license: null },
  },
  fr: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "Travailleurs indépendants de l’enquête LFS selon la citoyenneté. L’attribution à Eurostat est requise. Réutilisation libre avec mention de la source. La citoyenneté ne correspond ni au pays de naissance ni à la définition d’une entreprise sous contrôle étranger utilisée par les chambres de commerce.", license: "Réutilisation libre des données Eurostat avec attribution ; toute modification doit être signalée. Vérifié le 13 août 2026." },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS, tranche d’âge 20–64 ans. L’indicateur mesure la part des travailleurs indépendants dans l’emploi total au niveau UE-27, selon le groupe de citoyenneté. La citoyenneté est distincte du pays de naissance et de la définition d’entreprise étrangère du Registre des entreprises.", license: "Eurostat Statistics Explained / EU-LFS. Réutilisation soumise à l’attribution Eurostat et aux conditions de réutilisation applicables." },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "Registre des entreprises. InfoCamere définit comme « étrangère » une entreprise dans laquelle la participation globale de personnes physiques non nées en Italie dépasse 50 %, en combinant parts de participation et fonctions administratives selon la forme de l’entreprise. Le chiffre ne correspond pas au nombre d’entrepreneurs migrants et ne doit pas être comparé directement aux indicateurs LFS de travail indépendant.", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "Données du Registre des entreprises traitées par InfoCamere dans le cadre de Futurae. La contribution d’Unioncamere présente le stock d’entreprises à direction étrangère et le compare à l’ensemble du tissu entrepreneurial.", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "Taux de travail indépendant parmi la population occupée, selon le lieu de naissance. Les personnes nées à l’étranger et celles nées dans le pays sont des groupes de population, non des catégories de citoyenneté. Pour les pays européens sélectionnés, le chapitre s’appuie sur EU-LFS 2022 ; la moyenne OCDE couvre 37 pays. L’indicateur n’est pas un comptage d’entreprises enregistrées et ne doit pas être traité comme la même mesure que les données InfoCamere du Registre des entreprises.", license: null },
  },
  es: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "Trabajo autónomo de la LFS por ciudadanía. Se requiere atribución a Eurostat. Reutilización libre con reconocimiento de la fuente. La ciudadanía no equivale al país de nacimiento ni a la definición registral de empresa bajo control extranjero.", license: "Reutilización libre de Eurostat con atribución; deben indicarse las modificaciones, si las hubiera. Verificado el 13 de agosto de 2026." },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS, grupo de edad 20–64. El indicador es la proporción de trabajadores autónomos sobre el empleo total en la UE-27, por grupo de ciudadanía. La ciudadanía es distinta del país de nacimiento y de la definición de empresa extranjera del Registro de Empresas.", license: "Eurostat Statistics Explained / EU-LFS. Reutilización sujeta a la atribución a Eurostat y a las condiciones de reutilización aplicables." },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "Registro de Empresas. InfoCamere define como «extranjera» la empresa en la que la participación total de personas físicas no nacidas en Italia supera el 50 %, combinando cuotas de participación y cargos administrativos según el tipo de empresa. El dato no equivale al número de emprendedores migrantes y no debe compararse directamente con indicadores LFS de trabajo autónomo.", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "Datos del Registro de Empresas elaborados por InfoCamere en el marco de Futurae. La contribución de Unioncamere presenta el stock de empresas de dirección extranjera y lo compara con la base empresarial total.", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "Tasa de trabajo autónomo entre la población ocupada, por lugar de nacimiento. Las personas nacidas en el extranjero y en el país son grupos de población, no categorías de ciudadanía. Para los países europeos seleccionados, el capítulo utiliza EU-LFS 2022; la media de la OCDE cubre 37 países. El indicador no es un recuento de empresas registradas y no debe tratarse como la misma medida que los datos del Registro de Empresas de InfoCamere.", license: null },
  },
  de: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "LFS-Selbstständige nach Staatsangehörigkeit. Die Quelle Eurostat muss genannt werden. Freie Weiterverwendung mit Quellenangabe. Staatsangehörigkeit ist weder Geburtsland noch die kammerrechtliche Definition eines ausländisch kontrollierten Unternehmens.", license: "Freie Weiterverwendung von Eurostat mit Quellenangabe; Änderungen sind kenntlich zu machen. Geprüft am 13. August 2026." },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS, Altersgruppe 20–64. Der Indikator misst den Anteil der Selbstständigen an der Gesamtbeschäftigung auf EU-27-Ebene nach Staatsangehörigkeitsgruppe. Staatsangehörigkeit unterscheidet sich vom Geburtsland und von der Definition eines ausländischen Unternehmens im Unternehmensregister.", license: "Eurostat Statistics Explained / EU-LFS. Weiterverwendung unterliegt der Eurostat-Quellenangabe und den anwendbaren Nutzungsbedingungen." },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "Unternehmensregister. InfoCamere definiert ein Unternehmen als „ausländisch“, wenn die Gesamtbeteiligung natürlicher Personen, die nicht in Italien geboren wurden, über 50 % liegt; dabei werden Beteiligungsquoten und Verwaltungsfunktionen je nach Unternehmensform kombiniert. Die Zahl entspricht nicht der Anzahl migrantischer Unternehmer und darf nicht direkt mit LFS-Indikatoren zur Selbstständigkeit verglichen werden.", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "Daten des Unternehmensregisters, von InfoCamere im Rahmen von Futurae verarbeitet. Der Unioncamere-Beitrag weist den Bestand ausländisch geführter Unternehmen aus und vergleicht ihn mit der gesamten Unternehmensbasis.", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "Selbstständigenquote unter der erwerbstätigen Bevölkerung nach Geburtsort. Im Ausland und im Inland Geborene sind Bevölkerungsgruppen, keine Staatsangehörigkeitskategorien. Für die ausgewählten europäischen Länder stützt sich das Kapitel auf EU-LFS 2022; der OECD-Durchschnitt umfasst 37 Länder. Der Indikator ist keine Zählung registrierter Unternehmen und darf nicht als dieselbe Messgröße wie die InfoCamere-Daten des Unternehmensregisters behandelt werden.", license: null },
  },
  ar: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "بيانات مسح القوى العاملة عن العاملين لحسابهم الخاص حسب الجنسية. يجب نسب البيانات إلى Eurostat. إعادة الاستخدام مجانية مع ذكر المصدر. الجنسية لا تعادل بلد الميلاد ولا التعريف التجاري للمؤسسة الخاضعة لسيطرة أجنبية.", license: "إعادة استخدام بيانات Eurostat مجانية مع ذكر المصدر، مع بيان أي تعديلات. تم التحقق في 13 أغسطس 2026." },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS، الفئة العمرية 20–64 سنة. يقيس المؤشر حصة العاملين لحسابهم الخاص من إجمالي العمالة على مستوى الاتحاد الأوروبي-27 حسب مجموعة الجنسية. الجنسية تختلف عن بلد الميلاد وعن تعريف المؤسسة الأجنبية في سجل الشركات.", license: "Eurostat Statistics Explained / EU-LFS. تخضع إعادة الاستخدام لنسب المصدر إلى Eurostat ولشروط إعادة الاستخدام المعمول بها." },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "سجل الشركات. تعرّف InfoCamere المؤسسة «الأجنبية» بأنها المؤسسة التي تتجاوز فيها المشاركة الإجمالية للأشخاص الطبيعيين غير المولودين في إيطاليا 50%، مع الجمع بين حصص المشاركة والمناصب الإدارية بحسب نوع المؤسسة. لا يعادل الرقم عدد رواد الأعمال المهاجرين ولا ينبغي مقارنته مباشرة بمؤشرات العمل الحر في مسح القوى العاملة.", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "بيانات سجل الشركات التي عالجتها InfoCamere في إطار Futurae. يعرض إسهام Unioncamere رصيد المؤسسات ذات الإدارة الأجنبية ويقارنه بإجمالي قاعدة المؤسسات.", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "معدل العمل الحر ضمن السكان المشتغلين حسب مكان الميلاد. المولودون في الخارج والمولودون في البلد مجموعات سكانية وليست فئات جنسية. بالنسبة إلى الدول الأوروبية المختارة يعتمد الفصل على EU-LFS 2022؛ ويغطي متوسط OECD عدد 37 دولة. المؤشر ليس عدداً للمؤسسات المسجلة ولا ينبغي اعتباره القياس نفسه لبيانات سجل الشركات لدى InfoCamere.", license: null },
  },
  zh: {
    "81f45fae-8992-496c-a576-d6a528a53fb3": { methodology: "劳动力调查（LFS）按国籍划分的自雇数据。必须注明 Eurostat 来源。可在注明来源的条件下自由再利用。国籍不等同于出生国，也不等同于商会口径下的外资控制企业。", license: "Eurostat 数据可在注明来源的条件下自由再利用；如有修改应予说明。核验日期：2026年8月13日。" },
    "1f2db8e9-1e16-4a38-ac17-4122268a0b6a": { methodology: "EU-LFS，20–64岁年龄组。该指标衡量欧盟27国层面按国籍组划分的自雇人员占总就业人口的比例。国籍不同于出生国，也不同于企业注册簿对外国企业的定义。", license: "Eurostat Statistics Explained / EU-LFS。再利用须注明 Eurostat 来源并遵守适用的再利用条件。" },
    "0e567011-a622-4c4c-9c18-1a23465df64c": { methodology: "企业注册簿。InfoCamere 将“外国企业”定义为未出生于意大利的自然人总体参与比例超过50%的企业，并根据企业类型综合考虑持股份额和管理职务。该数据不等同于移民创业者人数，也不应与劳动力调查的自雇指标直接比较。", license: null },
    "18513fce-0483-4752-a171-df6c9afe926f": { methodology: "InfoCamere 在 Futurae 框架下处理的企业注册簿数据。Unioncamere 的材料报告外国经营企业的存量，并与整体企业基础进行比较。", license: null },
    "3b4f67ae-7399-4fc8-ac9e-7804bf30aed5": { methodology: "按出生地划分的就业人口自雇率。境外出生者与本国出生者属于人口组，而非国籍类别。对于所选欧洲国家，该章节采用 EU-LFS 2022；OECD 平均值覆盖37个国家。该指标不是登记企业数量，也不应与 InfoCamere 企业注册簿数据视为同一测量指标。", license: null },
  },
};

export function sourceTranslation(locale: Locale, id: string): SourceTranslation | null {
  return SOURCE_TRANSLATIONS[locale][id] ?? null;
}
