export type EditorialImageStockItem = {
  id: string;
  category: "Hero e leadership" | "Impresa e innovazione" | "Tecnologia e dati" | "Leadership femminile" | "Milano" | "Mobilità globale";
  title: string;
  photographer: string;
  pexelsUrl: string;
  imageUrl: string;
  suggestedUse: string;
  featured?: boolean;
};

export const EDITORIAL_IMAGE_STOCK: EditorialImageStockItem[] = [
  { id: "H01", category: "Hero e leadership", title: "Presentazione business in ufficio moderno", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/engaging-business-presentation-in-modern-office-34774353/", imageUrl: "https://images.pexels.com/photos/34774353/pexels-photo-34774353.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero attuale, leadership, conoscenza, impresa contemporanea", featured: true },
  { id: "H02", category: "Hero e leadership", title: "Keynote a conferenza tecnologica", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/keynote-speaker-at-technology-conference-34774347/", imageUrl: "https://images.pexels.com/photos/34774347/pexels-photo-34774347.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero alternativa, innovazione, visionari, eventi" },
  { id: "H03", category: "Hero e leadership", title: "Speaker a evento tecnologico", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/conference-speaker-at-technology-event-34774349/", imageUrl: "https://images.pexels.com/photos/34774349/pexels-photo-34774349.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Eventi, keynote, innovazione, leadership" },
  { id: "H04", category: "Hero e leadership", title: "Leader senior presenta a un team", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/a-man-in-black-suit-talking-beside-people-in-the-office-7654410/", imageUrl: "https://images.pexels.com/photos/7654410/pexels-photo-7654410.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership, mentoring, governance, impresa" },
  { id: "H05", category: "Hero e leadership", title: "Donna guida una presentazione aziendale", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/female-professional-standing-in-front-of-a-business-meeting-7647991/", imageUrl: "https://images.pexels.com/photos/7647991/pexels-photo-7647991.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership femminile, impresa, formazione" },
  { id: "H06", category: "Hero e leadership", title: "Presentazione con dati e strategia", photographer: "Mikhail Nilov", pexelsUrl: "https://www.pexels.com/photo/a-woman-making-a-business-presentation-6592676/", imageUrl: "https://images.pexels.com/photos/6592676/pexels-photo-6592676.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Dati, strategia, crescita, ricerca applicata" },
  { id: "H07", category: "Hero e leadership", title: "Presentazione professionale con pubblico", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/professional-business-presentation-in-modern-office-setting-34774351/", imageUrl: "https://images.pexels.com/photos/34774351/pexels-photo-34774351.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero, conferenze, leadership, knowledge economy" },
  { id: "H08", category: "Hero e leadership", title: "Speaker con schermi digitali", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/business-presentation-in-modern-office-setting-34774336/", imageUrl: "https://images.pexels.com/photos/34774336/pexels-photo-34774336.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero, tecnologia, comunicazione, eventi" },
  { id: "H09", category: "Hero e leadership", title: "Audience a presentazione business", photographer: "Mehmet BALCI", pexelsUrl: "https://www.pexels.com/photo/business-presentation-in-modern-office-setting-30319116/", imageUrl: "https://images.pexels.com/photos/30319116/pexels-photo-30319116.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Eventi, formazione, centro studi, networking" },
  { id: "H10", category: "Hero e leadership", title: "Presentazione finanziaria con grafici", photographer: "Kaboompics.com", pexelsUrl: "https://www.pexels.com/photo/man-making-a-presentation-in-an-office-7877014/", imageUrl: "https://images.pexels.com/photos/7877014/pexels-photo-7877014.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Mercati, dati, leadership, economia" },
  { id: "H11", category: "Hero e leadership", title: "Professionista parla al team", photographer: "Mikhail Nilov", pexelsUrl: "https://www.pexels.com/photo/a-man-speaking-in-the-office-9301738/", imageUrl: "https://images.pexels.com/photos/9301738/pexels-photo-9301738.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership, founder, impresa, mentoring" },
  { id: "H12", category: "Hero e leadership", title: "Presentazione con audience coinvolta", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/business-presentation-with-engaged-audience-in-modern-office-34774342/", imageUrl: "https://images.pexels.com/photos/34774342/pexels-photo-34774342.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero alternativa, eventi, impresa, conoscenza" },

  { id: "B01", category: "Impresa e innovazione", title: "Riunione professionale in ufficio moderno", photographer: "Vitaly Gariev", pexelsUrl: "https://www.pexels.com/photo/professional-business-meeting-in-modern-office-36733319/", imageUrl: "https://images.pexels.com/photos/36733319/pexels-photo-36733319.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "PMI, strategia, partnership, advisory" },
  { id: "B02", category: "Impresa e innovazione", title: "Meeting strategico tra professionisti", photographer: "Edmond Dantès", pexelsUrl: "https://www.pexels.com/photo/business-meeting-4342498/", imageUrl: "https://images.pexels.com/photos/4342498/pexels-photo-4342498.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Impresa, consulenza, decisioni, crescita" },
  { id: "B03", category: "Impresa e innovazione", title: "Team startup discute strategia", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/marketing-exit-office-technology-7414105/", imageUrl: "https://images.pexels.com/photos/7414105/pexels-photo-7414105.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, venture capital, founder, innovazione" },
  { id: "B04", category: "Impresa e innovazione", title: "Team multi-etnico al lavoro", photographer: "William Fortunato", pexelsUrl: "https://www.pexels.com/photo/crop-multiethnic-friends-working-on-startup-using-laptops-in-office-6140702/", imageUrl: "https://images.pexels.com/photos/6140702/pexels-photo-6140702.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, tecnologia, collaborazione, ricerca" },
  { id: "B05", category: "Impresa e innovazione", title: "Professionisti discutono dati e documenti", photographer: "Vitaly Gariev", pexelsUrl: "https://www.pexels.com/photo/business-meeting-in-modern-office-setting-36733299/", imageUrl: "https://images.pexels.com/photos/36733299/pexels-photo-36733299.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Osservatorio, dati, finanza, strategia" },
  { id: "B06", category: "Impresa e innovazione", title: "Team giovane in ambiente startup", photographer: "Ivan S", pexelsUrl: "https://www.pexels.com/photo/people-having-a-meeting-7213187/", imageUrl: "https://images.pexels.com/photos/7213187/pexels-photo-7213187.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, creatività, tecnologia, collaborazione" },
  { id: "B07", category: "Impresa e innovazione", title: "Giovani professionisti in startup", photographer: "Tima Miroshnichenko", pexelsUrl: "https://www.pexels.com/photo/young-professionals-working-together-inside-the-office-6913191/", imageUrl: "https://images.pexels.com/photos/6913191/pexels-photo-6913191.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, idee, team, crescita" },
  { id: "B08", category: "Impresa e innovazione", title: "Discussione su innovazione tecnologica", photographer: "Md Jawadur Rahman", pexelsUrl: "https://www.pexels.com/photo/team-discussion-on-technology-innovation-34987129/", imageUrl: "https://images.pexels.com/photos/34987129/pexels-photo-34987129.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Tecnologia, innovazione, strategia, team" },
  { id: "B09", category: "Impresa e innovazione", title: "Team startup in discussione", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/marketing-creative-exit-office-7414283/", imageUrl: "https://images.pexels.com/photos/7414283/pexels-photo-7414283.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Founder, venture, idee, crescita" },
  { id: "B10", category: "Impresa e innovazione", title: "Brainstorming con laptop e lavagna", photographer: "Thirdman", pexelsUrl: "https://www.pexels.com/photo/people-working-in-an-office-7180968/", imageUrl: "https://images.pexels.com/photos/7180968/pexels-photo-7180968.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Innovazione, planning, startup, team" },
  { id: "B11", category: "Impresa e innovazione", title: "Team software al lavoro", photographer: "cottonbro studio", pexelsUrl: "https://www.pexels.com/photo/employees-of-a-startup-software-company-chatting-while-working-6804603/", imageUrl: "https://images.pexels.com/photos/6804603/pexels-photo-6804603.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Software, impresa tech, collaborazione" },
  { id: "B12", category: "Impresa e innovazione", title: "Brainstorming di startup", photographer: "Tima Miroshnichenko", pexelsUrl: "https://www.pexels.com/photo/a-group-of-people-talking-about-start-up-business-6913193/", imageUrl: "https://images.pexels.com/photos/6913193/pexels-photo-6913193.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, strategia, ricerca, idee" },

  { id: "T01", category: "Tecnologia e dati", title: "Team professionale in spazio tecnologico", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/professional-team-working-in-office-space-34774356/", imageUrl: "https://images.pexels.com/photos/34774356/pexels-photo-34774356.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Tecnologia, software, innovazione" },
  { id: "T02", category: "Tecnologia e dati", title: "Sviluppatori al computer", photographer: "cottonbro studio", pexelsUrl: "https://www.pexels.com/photo/men-sitting-at-the-desks-in-an-office-and-using-computers-6804068/", imageUrl: "https://images.pexels.com/photos/6804068/pexels-photo-6804068.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Software, digitale, impresa tecnologica" },
  { id: "T03", category: "Tecnologia e dati", title: "Team condivide idee in spazio creativo", photographer: "Moe Magners", pexelsUrl: "https://www.pexels.com/photo/a-team-sharing-their-ideas-while-sitting-on-the-table-7495615/", imageUrl: "https://images.pexels.com/photos/7495615/pexels-photo-7495615.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Innovazione, design, startup, workshop" },
  { id: "T04", category: "Tecnologia e dati", title: "Startup team discute strategia", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/marketing-people-exit-office-7414217/", imageUrl: "https://images.pexels.com/photos/7414217/pexels-photo-7414217.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Founder, venture, tecnologia, crescita" },
  { id: "T05", category: "Tecnologia e dati", title: "Team al lavoro con computer", photographer: "Mizuno K", pexelsUrl: "https://www.pexels.com/photo/employees-working-on-computers-in-office-12903158/", imageUrl: "https://images.pexels.com/photos/12903158/pexels-photo-12903158.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Digitale, produttività, occupazione qualificata" },
  { id: "T06", category: "Tecnologia e dati", title: "Ricercatori davanti a schermi", photographer: "Darlene Alderson", pexelsUrl: "https://www.pexels.com/photo/brunette-woman-and-man-standing-by-screens-in-lab-4384666/", imageUrl: "https://images.pexels.com/photos/4384666/pexels-photo-4384666.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Ricerca, AI, data center, scienza" },
  { id: "T07", category: "Tecnologia e dati", title: "Control room con mappa globale", photographer: "SpaceX", pexelsUrl: "https://www.pexels.com/photo/group-of-colleagues-working-in-modern-office-with-big-map-on-screen-586104/", imageUrl: "https://images.pexels.com/photos/586104/pexels-photo-586104.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Dati globali, ricerca, tecnologia, monitoraggio" },
  { id: "T08", category: "Tecnologia e dati", title: "Team analizza grafici e report", photographer: "Kindel Media", pexelsUrl: "https://www.pexels.com/photo/planning-a-business-7688454/", imageUrl: "https://images.pexels.com/photos/7688454/pexels-photo-7688454.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Dati, analisi, strategia, osservatorio" },
  { id: "T09", category: "Tecnologia e dati", title: "Team discute business analytics", photographer: "Tiger Lily", pexelsUrl: "https://www.pexels.com/photo/a-group-of-people-having-a-meeting-in-the-office-7108816/", imageUrl: "https://images.pexels.com/photos/7108816/pexels-photo-7108816.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Analytics, management, tecnologia" },
  { id: "T10", category: "Tecnologia e dati", title: "Meeting con interfaccia digitale", photographer: "Mikhail Nilov", pexelsUrl: "https://www.pexels.com/photo/people-having-a-business-meeting-in-the-office-7988219/", imageUrl: "https://images.pexels.com/photos/7988219/pexels-photo-7988219.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Digital transformation, dati, innovazione" },

  { id: "W01", category: "Leadership femminile", title: "Business women in riunione", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/business-women-having-a-meeting-inside-the-office-8424530/", imageUrl: "https://images.pexels.com/photos/8424530/pexels-photo-8424530.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership femminile, strategia, board" },
  { id: "W02", category: "Leadership femminile", title: "Team di professioniste collabora", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/photo-of-women-at-the-office-8424525/", imageUrl: "https://images.pexels.com/photos/8424525/pexels-photo-8424525.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Imprenditrici, networking, leadership" },
  { id: "W03", category: "Leadership femminile", title: "Due manager in confronto", photographer: "Mizuno K", pexelsUrl: "https://www.pexels.com/photo/businesswomen-at-the-meeting-12903239/", imageUrl: "https://images.pexels.com/photos/12903239/pexels-photo-12903239.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Management, advisory, partnership" },
  { id: "W04", category: "Leadership femminile", title: "Senior executive guida il meeting", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/a-woman-in-a-blazer-during-a-meeting-8424521/", imageUrl: "https://images.pexels.com/photos/8424521/pexels-photo-8424521.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Executive leadership, governance, impresa" },
  { id: "W05", category: "Leadership femminile", title: "Tre professioniste in riunione", photographer: "Yan Krukau", pexelsUrl: "https://www.pexels.com/photo/women-having-a-meeting-at-the-office-8837196/", imageUrl: "https://images.pexels.com/photos/8837196/pexels-photo-8837196.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership, mentorship, collaborazione" },
  { id: "W06", category: "Leadership femminile", title: "Strategia in team femminile", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/business-women-having-a-meeting-inside-the-office-8424584/", imageUrl: "https://images.pexels.com/photos/8424584/pexels-photo-8424584.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Strategia, board, imprenditoria" },
  { id: "W07", category: "Leadership femminile", title: "Due professioniste discutono strategia", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/business-women-having-a-meeting-inside-the-office-8424580/", imageUrl: "https://images.pexels.com/photos/8424580/pexels-photo-8424580.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Decisioni, dati, leadership" },
  { id: "W08", category: "Leadership femminile", title: "Gruppo di donne con laptop", photographer: "Alena Shekhovtcova", pexelsUrl: "https://www.pexels.com/photo/women-on-a-meeting-in-an-office-8067833/", imageUrl: "https://images.pexels.com/photos/8067833/pexels-photo-8067833.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, tecnologia, imprenditrici" },
  { id: "W09", category: "Leadership femminile", title: "Business strategy tra professioniste", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/business-women-having-a-meeting-inside-the-office-8424574/", imageUrl: "https://images.pexels.com/photos/8424574/pexels-photo-8424574.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Management, strategia, progetto" },
  { id: "W10", category: "Leadership femminile", title: "Businesswoman in team meeting", photographer: "Gustavo Fring", pexelsUrl: "https://www.pexels.com/photo/businesswoman-in-suit-in-meeting-4872020/", imageUrl: "https://images.pexels.com/photos/4872020/pexels-photo-4872020.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Executive, leadership, business" },
  { id: "W11", category: "Leadership femminile", title: "Executive in boardroom", photographer: "MART PRODUCTION", pexelsUrl: "https://www.pexels.com/photo/person-people-woman-office-7222945/", imageUrl: "https://images.pexels.com/photos/7222945/pexels-photo-7222945.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Profilo executive, governance, leadership" },
  { id: "W12", category: "Leadership femminile", title: "Team multiculturale in discussione", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/woman-taking-notes-of-business-meeting-in-office-8068807/", imageUrl: "https://images.pexels.com/photos/8068807/pexels-photo-8068807.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Impresa, diversity, strategia, management" },

  { id: "M01", category: "Milano", title: "Architettura contemporanea nel distretto business", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-urban-architecture-in-milan-s-business-district-36511357/", imageUrl: "https://images.pexels.com/photos/36511357/pexels-photo-36511357.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, capitale economica, territori, eventi" },
  { id: "M02", category: "Milano", title: "Skyline e uffici contemporanei", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-office-buildings-in-milan-cityscape-36538100/", imageUrl: "https://images.pexels.com/photos/36538100/pexels-photo-36538100.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, mercati, economia urbana, territorio" },
  { id: "M03", category: "Milano", title: "Ufficio moderno a Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-milano-office-interior-with-natural-light-36497528/", imageUrl: "https://images.pexels.com/photos/36497528/pexels-photo-36497528.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, lavoro, innovazione, corporate" },
  { id: "M04", category: "Milano", title: "Skyline visto dal Duomo", photographer: "Bruna Santos", pexelsUrl: "https://www.pexels.com/photo/skyline-view-of-milan-from-duomo-di-milano-36464754/", imageUrl: "https://images.pexels.com/photos/36464754/pexels-photo-36464754.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, territorio, città globale" },
  { id: "M05", category: "Milano", title: "Piazza del Duomo e skyline", photographer: "Ana Benet", pexelsUrl: "https://www.pexels.com/photo/sky-over-the-piazza-del-duomo-8243237/", imageUrl: "https://images.pexels.com/photos/8243237/pexels-photo-8243237.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, identità urbana, cultura" },
  { id: "M06", category: "Milano", title: "Skyscrapers nel business district", photographer: "Vanja Djakovic", pexelsUrl: "https://www.pexels.com/photo/modern-skyscrapers-in-milan-s-business-district-36835318/", imageUrl: "https://images.pexels.com/photos/36835318/pexels-photo-36835318.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, finanza, impresa, città globale" },
  { id: "M07", category: "Milano", title: "Architettura di Porta Nuova", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-architecture-in-milan-s-porta-nuova-37132656/", imageUrl: "https://images.pexels.com/photos/37132656/pexels-photo-37132656.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, urban economy, innovazione" },
  { id: "M08", category: "Milano", title: "Torre UniCredit e Porta Nuova", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-skyscrapers-in-milano-s-porta-nuova-district-37132647/", imageUrl: "https://images.pexels.com/photos/37132647/pexels-photo-37132647.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, finanza, mercati, economia" },
  { id: "M09", category: "Milano", title: "Edificio per uffici contemporaneo", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-office-building-architecture-in-milan-38773619/", imageUrl: "https://images.pexels.com/photos/38773619/pexels-photo-38773619.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Corporate, Milano, innovazione urbana" },
  { id: "M10", category: "Milano", title: "Skyscrapers e cielo di Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-skyscrapers-reaching-for-blue-sky-in-milan-36302356/", imageUrl: "https://images.pexels.com/photos/36302356/pexels-photo-36302356.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Crescita, business district, Milano" },
  { id: "M11", category: "Milano", title: "Architettura verticale contemporanea", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-skyscraper-architecture-in-milan-36287486/", imageUrl: "https://images.pexels.com/photos/36287486/pexels-photo-36287486.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, innovazione, infrastrutture" },
  { id: "M12", category: "Milano", title: "Skyline moderno di Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-skyline-of-milan-featuring-iconic-towers-36844553/", imageUrl: "https://images.pexels.com/photos/36844553/pexels-photo-36844553.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, economia, territorio, apertura internazionale" },

  { id: "G01", category: "Mobilità globale", title: "Professionisti in aeroporto", photographer: "Gustavo Fring", pexelsUrl: "https://www.pexels.com/photo/cheerful-business-people-with-passport-in-airport-hall-4173205/", imageUrl: "https://images.pexels.com/photos/4173205/pexels-photo-4173205.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Mobilità, business travel, internazionalizzazione" },
  { id: "G02", category: "Mobilità globale", title: "Terminal internazionale", photographer: "Magic K", pexelsUrl: "https://www.pexels.com/photo/busy-people-on-the-airport-terminal-6726195/", imageUrl: "https://images.pexels.com/photos/6726195/pexels-photo-6726195.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Mobilità, rotte, persone, territori" },
  { id: "G03", category: "Mobilità globale", title: "Viaggiatori in terminal moderno", photographer: "Rafael Rodrigues", pexelsUrl: "https://www.pexels.com/photo/people-at-airport-16108892/", imageUrl: "https://images.pexels.com/photos/16108892/pexels-photo-16108892.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Rotte, mobilità internazionale, diaspora" },
  { id: "G04", category: "Mobilità globale", title: "Business traveler in aeroporto", photographer: "Jan van der Wolf", pexelsUrl: "https://www.pexels.com/photo/man-in-suit-sitting-on-bench-in-terminal-14805998/", imageUrl: "https://images.pexels.com/photos/14805998/pexels-photo-14805998.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Mobilità professionale, mercati, connessioni" },
  { id: "G05", category: "Mobilità globale", title: "Container e logistica globale", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/cargo-containers-in-a-port-8783533/", imageUrl: "https://images.pexels.com/photos/8783533/pexels-photo-8783533.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Commercio internazionale, supply chain, mercati" },
  { id: "G06", category: "Mobilità globale", title: "Porto e commercio internazionale", photographer: "Jimmy Chan", pexelsUrl: "https://www.pexels.com/photo/cargo-containers-at-the-port-12999283/", imageUrl: "https://images.pexels.com/photos/12999283/pexels-photo-12999283.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Asia, commercio, logistica, export" },
  { id: "G07", category: "Mobilità globale", title: "Porto europeo e container", photographer: "James Heming", pexelsUrl: "https://www.pexels.com/photo/cargo-containers-in-a-port-4570838/", imageUrl: "https://images.pexels.com/photos/4570838/pexels-photo-4570838.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Europa, commercio, logistica, infrastrutture" },
  { id: "G08", category: "Mobilità globale", title: "Cargo ship e container", photographer: "lucas hegaard", pexelsUrl: "https://www.pexels.com/photo/cargo-ship-with-containers-in-shipping-port-30115463/", imageUrl: "https://images.pexels.com/photos/30115463/pexels-photo-30115463.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Supply chain, export, commercio globale" },
  { id: "G09", category: "Mobilità globale", title: "Team con mappa del mondo", photographer: "Gustavo Fring", pexelsUrl: "https://www.pexels.com/photo/people-at-office-4872021/", imageUrl: "https://images.pexels.com/photos/4872021/pexels-photo-4872021.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Reti internazionali, strategia, mercati" },
  { id: "G10", category: "Mobilità globale", title: "Team multiculturale in ufficio", photographer: "Mikhail Nilov", pexelsUrl: "https://www.pexels.com/photo/people-in-the-office-9301835/", imageUrl: "https://images.pexels.com/photos/9301835/pexels-photo-9301835.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Impresa globale, talenti, reti, diaspora" },
];
