export type EditorialImageStockItem = {
  id: string;
  category: "Leadership" | "Impresa e innovazione" | "Milano";
  title: string;
  photographer: string;
  pexelsUrl: string;
  imageUrl: string;
  suggestedUse: string;
};

export const EDITORIAL_IMAGE_STOCK: EditorialImageStockItem[] = [
  { id: "L01", category: "Leadership", title: "Presentazione business in ufficio moderno", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/engaging-business-presentation-in-modern-office-34774353/", imageUrl: "https://images.pexels.com/photos/34774353/pexels-photo-34774353.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Hero, leadership, conoscenza, impresa contemporanea" },
  { id: "L02", category: "Leadership", title: "Keynote a conferenza tecnologica", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/keynote-speaker-at-technology-conference-34774347/", imageUrl: "https://images.pexels.com/photos/34774347/pexels-photo-34774347.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Innovazione, visionari, eventi, interviste" },
  { id: "L03", category: "Leadership", title: "Speaker a evento tecnologico", photographer: "Matheus Bertelli", pexelsUrl: "https://www.pexels.com/photo/conference-speaker-at-technology-event-34774349/", imageUrl: "https://images.pexels.com/photos/34774349/pexels-photo-34774349.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Eventi, keynote, innovazione, leadership" },
  { id: "L04", category: "Leadership", title: "Leader senior presenta a un team diversificato", photographer: "Pavel Danilyuk", pexelsUrl: "https://www.pexels.com/photo/a-man-in-black-suit-talking-beside-people-in-the-office-7654410/", imageUrl: "https://images.pexels.com/photos/7654410/pexels-photo-7654410.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership, mentoring, governance, impresa" },
  { id: "L05", category: "Leadership", title: "Donna guida una presentazione aziendale", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/female-professional-standing-in-front-of-a-business-meeting-7647991/", imageUrl: "https://images.pexels.com/photos/7647991/pexels-photo-7647991.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Leadership femminile, impresa, formazione" },
  { id: "L06", category: "Leadership", title: "Presentazione con dati e strategia", photographer: "Mikhail Nilov", pexelsUrl: "https://www.pexels.com/photo/a-woman-making-a-business-presentation-6592676/", imageUrl: "https://images.pexels.com/photos/6592676/pexels-photo-6592676.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Dati, strategia, crescita, ricerca applicata" },
  { id: "I01", category: "Impresa e innovazione", title: "Riunione professionale in ufficio moderno", photographer: "Vitaly Gariev", pexelsUrl: "https://www.pexels.com/photo/professional-business-meeting-in-modern-office-36733319/", imageUrl: "https://images.pexels.com/photos/36733319/pexels-photo-36733319.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "PMI, strategia, partnership, advisory" },
  { id: "I02", category: "Impresa e innovazione", title: "Meeting strategico tra professionisti", photographer: "Edmond Dantès", pexelsUrl: "https://www.pexels.com/photo/business-meeting-4342498/", imageUrl: "https://images.pexels.com/photos/4342498/pexels-photo-4342498.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Impresa, consulenza, decisioni, crescita" },
  { id: "I03", category: "Impresa e innovazione", title: "Team startup discute strategia", photographer: "RDNE Stock project", pexelsUrl: "https://www.pexels.com/photo/marketing-exit-office-technology-7414105/", imageUrl: "https://images.pexels.com/photos/7414105/pexels-photo-7414105.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, venture capital, founder, innovazione" },
  { id: "I04", category: "Impresa e innovazione", title: "Team multi-etnico al lavoro su un progetto", photographer: "William Fortunato", pexelsUrl: "https://www.pexels.com/photo/crop-multiethnic-friends-working-on-startup-using-laptops-in-office-6140702/", imageUrl: "https://images.pexels.com/photos/6140702/pexels-photo-6140702.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, tecnologia, collaborazione, ricerca" },
  { id: "I05", category: "Impresa e innovazione", title: "Professionisti discutono dati e documenti", photographer: "Vitaly Gariev", pexelsUrl: "https://www.pexels.com/photo/business-meeting-in-modern-office-setting-36733299/", imageUrl: "https://images.pexels.com/photos/36733299/pexels-photo-36733299.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Osservatorio, dati, finanza, strategia" },
  { id: "I06", category: "Impresa e innovazione", title: "Team giovane in ambiente startup", photographer: "Ivan S", pexelsUrl: "https://www.pexels.com/photo/people-having-a-meeting-7213187/", imageUrl: "https://images.pexels.com/photos/7213187/pexels-photo-7213187.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Startup, creatività, tecnologia, collaborazione" },
  { id: "M01", category: "Milano", title: "Architettura contemporanea nel distretto business di Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-urban-architecture-in-milan-s-business-district-36511357/", imageUrl: "https://images.pexels.com/photos/36511357/pexels-photo-36511357.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, capitale economica, territori, eventi" },
  { id: "M02", category: "Milano", title: "Skyline e uffici contemporanei di Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-office-buildings-in-milan-cityscape-36538100/", imageUrl: "https://images.pexels.com/photos/36538100/pexels-photo-36538100.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, mercati, economia urbana, territorio" },
  { id: "M03", category: "Milano", title: "Ufficio moderno a Milano", photographer: "Earth Photart", pexelsUrl: "https://www.pexels.com/photo/modern-milano-office-interior-with-natural-light-36497528/", imageUrl: "https://images.pexels.com/photos/36497528/pexels-photo-36497528.jpeg?auto=compress&cs=tinysrgb&w=1200", suggestedUse: "Milano, lavoro, innovazione, corporate" },
];
